version: "3.9"

services:
  regback:
    container_name: regback
    build: ./back
    command: python reguser/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=db
    tty: true
    restart: always
    depends_on:
      - db
    networks:
      - net
    volumes:
      - ./back:/app

  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
      - net
    volumes:
      - ./db:/var/lib/postgresql/data

  web:
    container_name: reguserfront
    image: node:lts-slim
    ports:
      - "3000:3000"
    tty: true
    restart: always
    depends_on:
      - regback
    networks:
      - net
    volumes:
      - ./front:/app

volumes:
  pgdata: {}

networks:
  net:
