# Generated by Django 5.0.7 on 2024-08-24 06:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('adwords', models.BooleanField(default=False, verbose_name='Реклама')),
                ('adwords_start', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала рекламы')),
                ('adwords_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания рекламы')),
                ('premium', models.BooleanField(default=False, verbose_name='Премиум')),
                ('premium_start', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала премиума')),
                ('premium_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания премиума')),
                ('show', models.BooleanField(default=True, verbose_name='Показывать')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('special_offer', models.BooleanField(default=False, verbose_name='Специальное предложение')),
                ('special_offer_start', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала специального предложения')),
                ('special_offer_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания специального предложения')),
                ('special_offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена специального предложения')),
                ('special_offer_description', models.TextField(blank=True, null=True, verbose_name='Описание специального предложения')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение 4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение 5')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение 6')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение 7')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение 8')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение 9')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение 10')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=255, verbose_name='Электронная почта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('site', models.URLField(max_length=255, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='FeedbackProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(verbose_name='Оценка продукта')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='feedbacks/', verbose_name='Изображение 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='feedbacks/', verbose_name='Изображение 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='feedbacks/', verbose_name='Изображение 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='feedbacks/', verbose_name='Изображение 4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='feedbacks/', verbose_name='Изображение 5')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Отзыв о продукте',
                'verbose_name_plural': 'Отзывы о продуктах',
            },
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=255, verbose_name='Электронная почта')),
                ('date', models.DateField(verbose_name='Дата')),
                ('number', models.CharField(max_length=255, verbose_name='Номер сертификата')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='Изображение сертификата')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='app.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.seller', verbose_name='Продавец'),
        ),
        migrations.CreateModel(
            name='FeedbackSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(verbose_name='Оценка продавца')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='feedbacks/', verbose_name='Изображение 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='feedbacks/', verbose_name='Изображение 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='feedbacks/', verbose_name='Изображение 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='feedbacks/', verbose_name='Изображение 4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='feedbacks/', verbose_name='Изображение 5')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app.seller', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Отзыв о продавце',
                'verbose_name_plural': 'Отзывы о продавцах',
            },
        ),
    ]
