# Generated by Django 5.0.7 on 2024-08-24 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='certificate_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание сертификата'),
        ),
        migrations.AddField(
            model_name='product',
            name='certificate_langth_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок действия сертификата (дней)'),
        ),
        migrations.AddField(
            model_name='product',
            name='certificate_template',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Шаблон сертификата'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.TextField(blank=True, null=True, verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='public_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания публикации'),
        ),
        migrations.AddField(
            model_name='product',
            name='public_length_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок публикации (дней)'),
        ),
        migrations.AddField(
            model_name='product',
            name='public_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала публикации'),
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.TextField(blank=True, null=True, verbose_name='Политика возврата'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='app.tags', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='seller',
            name='about',
            field=models.TextField(default='', verbose_name='О продавце'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='sellers/', verbose_name='Изображение 1'),
        ),
        migrations.AddField(
            model_name='seller',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='sellers/', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='seller',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='sellers/', verbose_name='Изображение 3'),
        ),
        migrations.AddField(
            model_name='seller',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='sellers/', verbose_name='Изображение 4'),
        ),
        migrations.AddField(
            model_name='seller',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='sellers/', verbose_name='Изображение 5'),
        ),
        migrations.AddField(
            model_name='seller',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sellers/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='seller',
            name='social1',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Соцсеть 1'),
        ),
        migrations.AddField(
            model_name='seller',
            name='social2',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Соцсеть 2'),
        ),
        migrations.AddField(
            model_name='seller',
            name='social3',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Соцсеть 3'),
        ),
        migrations.AddField(
            model_name='seller',
            name='social4',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Соцсеть 4'),
        ),
        migrations.DeleteModel(
            name='FeedbackProduct',
        ),
    ]
