# Generated by Django 5.0.7 on 2024-08-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_view_count_seller_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='app.tags', verbose_name='Теги'),
        ),
    ]
