# Generated by Django 5.0.7 on 2024-08-30 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='premium',
        ),
        migrations.RemoveField(
            model_name='product',
            name='premium_end',
        ),
        migrations.RemoveField(
            model_name='product',
            name='premium_start',
        ),
        migrations.RemoveField(
            model_name='product',
            name='show',
        ),
    ]
