# Generated by Django 5.0.7 on 2024-08-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_birth_date_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium',
            field=models.BooleanField(default=False, verbose_name='Премиум'),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания премиума'),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала премиума'),
        ),
    ]
