# Generated by Django 5.0.7 on 2024-08-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_premium_profile_premium_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='actual_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фактический адрес'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Расчетный счет'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_bik',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_correspondent',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Корреспондентский счет'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка'),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='profile',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='profile',
            name='legal_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ogrn',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='profile',
            name='products_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество объявлений'),
        ),
        migrations.AddField(
            model_name='profile',
            name='products_limit',
            field=models.PositiveIntegerField(default=5, verbose_name='Лимит объявлений'),
        ),
        migrations.AddField(
            model_name='profile',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт'),
        ),
    ]
